Repository DZDcyj/QSGS-v2-Lua, pull requests merged in 2023-09, with the labels that each got.

#805 fix: 修正司马徽【隐士】问题
  .gitignore
  audio/skill/chenghao1.ogg
  audio/skill/chenghao2.ogg
  audio/skill/jianjie1.ogg
  audio/skill/jianjie2.ogg
  audio/skill/jianjie3.ogg
  audio/skill/simahui.ogg
  audio/skill/yinshi1.ogg
  audio/skill/yinshi2.ogg
  extensions/extra.lua
Labels: bug, 🔍 Ready for Review, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#807 fix: 调整文鸯【却敌】背水选项顺序
  extensions/LayingPlansCouragePackage.lua
  extensions/extra.lua
  lang/zh_CN/Package/LayingPlansCouragePackage.lua
Labels: general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#809 ci: 优化打包流程
  .github/workflows/auto-release.yml
Labels: github issue, ✅ Approved

#804 fix: 饿人类技能重做
  extensions/GroupFriendPackage.lua
  lang/zh_CN/Package/GroupFriendPackage.lua
Labels: general fix, ✅ Approved, 🌵 Cactusssssssss

#813 fix: 调整饿人类技能
  extensions/GroupFriendPackage.lua
  lang/zh_CN/Package/GroupFriendPackage.lua
Labels: general fix, 🔍 Ready for Review, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#815 feat: 添加承·关羽
  Generals.md
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/ExChengguanyu.png
  image/generals/card/ExChengguanyu.jpg
  lang/zh_CN/Package/ExpansionPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#817 feat: 添加新版诸葛瞻
  Generals.md
  audio/skill/ExZhugezhan.ogg
  audio/skill/LuaFuyin1.ogg
  audio/skill/LuaFuyin2.ogg
  audio/skill/LuaZuilun1.ogg
  audio/skill/LuaZuilun2.ogg
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/ExZhugezhan.png
  image/generals/card/ExZhugezhan.jpg
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#820 feat: 增补界卧龙诸葛语音
  audio/skill/JieWolong.ogg
  audio/skill/LuaBazhen1.ogg
  audio/skill/LuaBazhen2.ogg
  audio/skill/LuaCangzhuo1.ogg
  audio/skill/LuaCangzhuo2.ogg
  audio/skill/LuaHuoji1.ogg
  audio/skill/LuaHuoji2.ogg
  audio/skill/LuaKanpo1.ogg
  audio/skill/LuaKanpo2.ogg
  extensions/ExpansionPackage.lua
  lang/zh_CN/Audio/ExpansionPackageLines.lua
Labels: general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#821 feat: 添加 OL 张翼
  Generals.md
  audio/skill/LuaDianjun1.ogg
  audio/skill/LuaDianjun2.ogg
  audio/skill/LuaKangrui1.ogg
  audio/skill/LuaKangrui2.ogg
  audio/skill/OLZhangyi.ogg
  extensions/ExpansionPackage.lua
  extensions/OLBoundaryBreachFirePackage.lua
  image/fullskin/generals/full/OLZhangyi.png
  image/generals/card/OLZhangyi.jpg
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Audio/OLBoundaryBreachFirePackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
  lang/zh_CN/Package/OLBoundaryBreachFirePackage.lua
Labels: enhancement, 🔍 Ready for Review, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#826 feat: 添加傅佥
  Generals.md
  audio/skill/ExFuqian.ogg
  audio/skill/LuaJueyong1.ogg
  audio/skill/LuaJueyong2.ogg
  audio/skill/LuaPoxiang1.ogg
  audio/skill/LuaPoxiang2.ogg
  extensions/ExpansionPackage.lua
  extensions/LayingPlansSincerityPackage.lua
  image/fullskin/generals/full/ExFuqian.png
  image/generals/card/ExFuqian.jpg
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#808 feat: 添加米糠
  Generals.md
  extensions/ExpansionPackage.lua
  extensions/GroupFriendPackage.lua
  extensions/LandlordsPackage.lua
  extensions/RectificationPackage.lua
  image/fullskin/generals/full/Mikang.png
  image/generals/card/Mikang.jpg
  lang/zh_CN/Package/GroupFriendPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, ✅ Approved, 🌵 Cactusssssssss

#830 fix: 调整阿杰技能
  extensions/GroupFriendPackage.lua
  lang/zh_CN/Package/GroupFriendPackage.lua
  lua/ai/GroupFriendPackage-ai.lua
Labels: general fix, 🔍 Ready for Review, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#828 fix: 修正司马徽【称好】问题
  extensions/extra.lua
Labels: bug, ✅ Approved, 👨‍🔬 Rinkosanvsky

#834 fix: 修正阿杰素来言出必践技能图标，修改成圣触发频率，修正sp仙人掌绝杀技能描述
  extensions/GroupFriendPackage.lua
  lang/zh_CN/Package/GroupFriendPackage.lua
Labels: ✅ Approved, 👨‍🔬 Rinkosanvsky

#833 fix: 修正神太史慈技能名称
  audio/skill/LuaShenzhuo1.ogg
  audio/skill/LuaShenzhuo2.ogg
  extensions/LayingPlansSincerityPackage.lua
  image/heroskin/audio/ExShenTaishici_1/skill/LuaShenzhuo1.ogg
  image/heroskin/audio/ExShenTaishici_1/skill/LuaShenzhuo2.ogg
  image/heroskin/audio/ExShenTaishici_2/death/ExShenTaishici.ogg
  image/heroskin/audio/ExShenTaishici_2/skill/LuaDulie1.ogg
  image/heroskin/audio/ExShenTaishici_2/skill/LuaDulie2.ogg
  image/heroskin/audio/ExShenTaishici_2/skill/LuaPowei1.ogg
  image/heroskin/audio/ExShenTaishici_2/skill/LuaPowei2.ogg
  image/heroskin/audio/ExShenTaishici_2/skill/LuaPowei3.ogg
  image/heroskin/audio/ExShenTaishici_2/skill/LuaShenzhuo1.ogg
  image/heroskin/audio/ExShenTaishici_2/skill/LuaShenzhuo2.ogg
  image/heroskin/fullskin/generals/full/ExShenTaishici_2.png
  image/heroskin/generals/card/ExShenTaishici_2.jpg
  image/heroskin/lang/zh_CN/Audio/StandardGeneralPackageLines.lua
  lang/zh_CN/Audio/LayingPlansSincerityPackageLines.lua
  lang/zh_CN/Package/LayingPlansSincerityPackage.lua
Labels: enhancement, general fix, ✅ Approved, 🌵 Cactusssssssss

#836 fix: 调整 PR 模板
  .github/pull_request_template.md
Labels: documentation, ✅ Approved, 👨‍🔬 Rinkosanvsky

#838 fix: 修正取消目标技能重复判定问题
  extensions/ExpansionPackage.lua
  extensions/GroupFriendPackage.lua
  extensions/LayingPlansSincerityPackage.lua
Labels: bug, ✅ Approved, 👨‍🔬 Rinkosanvsky

#839 docs: 更新 Readme
  README.md
Labels: documentation, 🔍 Ready for Review, ✅ Approved, 👨‍🔬 Rinkosanvsky

#840 docs: 追加补充说明
  README.md
  lua/config.lua
Labels: documentation, ✅ Approved

#843 feat: 添加 OL 界典韦
  Generals.md
  audio/skill/LuaOLNinge1.ogg
  audio/skill/LuaOLNinge2.ogg
  audio/skill/LuaOLQiangxi1.ogg
  audio/skill/LuaOLQiangxi2.ogg
  audio/skill/OLJieDianwei.ogg
  extensions/LayingPlansSincerityPackage.lua
  extensions/OLBoundaryBreachFirePackage.lua
  image/fullskin/generals/full/OLJieDianwei.png
  image/generals/card/OLJieDianwei.jpg
  lang/zh_CN/Audio/OLBoundaryBreachFirePackageLines.lua
  lang/zh_CN/Package/OLBoundaryBreachFirePackage.lua
Labels: enhancement, ✅ Approved, 🌵 Cactusssssssss

#846 refactor: 拆分手杀-界一将成名 2013 武将包
  .gitignore
  Generals.md
  audio/skill/JieLiru.ogg
  audio/skill/LuaFencheng1.ogg
  audio/skill/LuaFencheng2.ogg
  audio/skill/LuaJuece1.ogg
  audio/skill/LuaJuece2.ogg
  audio/skill/LuaMieji1.ogg
  audio/skill/LuaMieji2.ogg
  extensions/ExpansionPackage.lua
  extensions/MobileJieYJCM2013Package.lua
  image/generals/card/JieLiru.jpg
  image/heroskin/audio/JieLiru_1/death/JieLiru.ogg
  image/heroskin/audio/JieLiru_1/skill/LuaFencheng1.ogg
  image/heroskin/audio/JieLiru_1/skill/LuaFencheng2.ogg
  image/heroskin/audio/JieLiru_1/skill/LuaJuece1.ogg
  image/heroskin/audio/JieLiru_1/skill/LuaJuece2.ogg
  image/heroskin/audio/JieLiru_1/skill/LuaMieji1.ogg
  image/heroskin/audio/JieLiru_1/skill/LuaMieji2.ogg
  image/heroskin/fullskin/generals/full/JieLiru_1.png
  image/heroskin/generals/card/JieLiru_1.jpg
  image/heroskin/lang/zh_CN/Audio/StandardGeneralPackageLines.lua
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Audio/MobileJieYJCM2013PackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
  lang/zh_CN/Package/MobileJieYJCM2013Package.lua
  lua/ai/ExpansionPackage-ai.lua
  lua/ai/MobileJieYJCM2013Package-ai.lua
Labels: general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#845 feat: 添加杨仪
  Generals.md
  audio/skill/ExYangyi.ogg
  audio/skill/LuaDuoduan1.ogg
  audio/skill/LuaDuoduan2.ogg
  audio/skill/LuaGongsun1.ogg
  audio/skill/LuaGongsun2.ogg
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/ExYangyi.png
  image/generals/card/ExYangyi.jpg
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: enhancement, ✅ Approved, 🌵 Cactusssssssss
