Repository DZDcyj/QSGS-v2-Lua, pull requests merged in 2023-04, with the labels that each got.

#675 feat: 添加谋夏侯氏
  audio/skill/ExMouXiahoushi.ogg
  audio/skill/LuaMouQiaoshi1.ogg
  audio/skill/LuaMouQiaoshi2.ogg
  audio/skill/LuaMouYanyu1.ogg
  audio/skill/LuaMouYanyu2.ogg
  extensions/ExpansionPackage.lua
  extensions/StrategicAttackTogetherPackage.lua
  image/fullskin/generals/full/ExMouXiahoushi.png
  image/generals/card/ExMouXiahoushi.jpg
  lang/zh_CN/Audio/StrategicAttackTogetherPackageLines.lua
  lang/zh_CN/Package/StrategicAttackTogetherPackage.lua
  lua/QSanguoshaLuaFunction.lua
  lua/ai/StrategicAttackTogetherPackage-ai.lua
Labels: enhancement, general fix, ✅ Approved, 🌵 Cactusssssssss

#677 feat: 添加费祎
  .gitignore
  Generals.md
  audio/skill/ExFeiyi.ogg
  audio/skill/LuaJianyu1.ogg
  audio/skill/LuaJianyu2.ogg
  audio/skill/LuaShengxi1.ogg
  audio/skill/LuaShengxi2.ogg
  extensions/ExpansionCardPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  image/big-card/adjust_salt_plum.png
  image/card/adjust_salt_plum.png
  image/fullskin/generals/full/ExFeiyi.png
  image/generals/card/ExFeiyi.jpg
  image/mark/@LuaJianyu.png
  lang/zh_CN/Audio/LayingPlansWisdomPackageLines.lua
  lang/zh_CN/Package/ExpansionCardPackage.lua
  lang/zh_CN/Package/LayingPlansWisdomPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, ✅ Approved, 🌵 Cactusssssssss

#678 fix: 文鸯【椎锋】失效期限修正
  extensions/LayingPlansCouragePackage.lua
  lang/zh_CN/Package/LayingPlansCouragePackage.lua
Labels: bug, ✅ Approved, 🌵 Cactusssssssss

#679 fix: 调整斗地主模式势力选择时机
  extensions/LandlordsPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky

#680 feat: 添加 OL 界华雄
  Generals.md
  audio/skill/LuaOLShizhan1.ogg
  audio/skill/LuaOLShizhan2.ogg
  audio/skill/LuaOLYaowu1.ogg
  audio/skill/LuaOLYaowu2.ogg
  audio/skill/OLJieHuaxiong.ogg
  extensions/ExpansionPackage.lua
  extensions/LayingPlansCouragePackage.lua
  image/fullskin/generals/full/OLJieHuaxiong.png
  image/generals/card/OLJieHuaxiong.jpg
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: enhancement, general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#681 fix: 界徐盛卡面调整与新皮肤
  audio/skill/JieXusheng.ogg
  audio/skill/LuaPojun1.ogg
  audio/skill/LuaPojun2.ogg
  image/fullskin/generals/full/JieXusheng.png
  image/generals/card/JieXusheng.jpg
  image/heroskin/audio/JieXusheng_3/death/JieXusheng.ogg
  image/heroskin/audio/JieXusheng_3/skill/LuaPojun1.ogg
  image/heroskin/audio/JieXusheng_3/skill/LuaPojun2.ogg
  image/heroskin/audio/JieXusheng_4/death/JieXusheng.ogg
  image/heroskin/audio/JieXusheng_4/skill/LuaPojun1.ogg
  image/heroskin/audio/JieXusheng_4/skill/LuaPojun2.ogg
  image/heroskin/fullskin/generals/full/JieXusheng_3.png
  image/heroskin/fullskin/generals/full/JieXusheng_4.png
  image/heroskin/generals/card/JieXusheng_3.jpg
  image/heroskin/generals/card/JieXusheng_4.jpg
  image/heroskin/lang/zh_CN/Audio/StandardGeneralPackageLines.lua
  lang/zh_CN/Audio/ExpansionPackageLines.lua
Labels: enhancement, general fix, ✅ Approved, 🌵 Cactusssssssss

#682 fix: 界满宠卡面调整与新皮肤
  audio/skill/JieManchong.ogg
  audio/skill/LuaJunxing1.ogg
  audio/skill/LuaJunxing2.ogg
  audio/skill/LuaYuce1.ogg
  audio/skill/LuaYuce2.ogg
  extensions/ExpansionPackage.lua
  image/generals/card/JieManchong.jpg
  image/heroskin/audio/JieManchong_1/death/JieManchong.ogg
  image/heroskin/audio/JieManchong_1/skill/LuaJunxing1.ogg
  image/heroskin/audio/JieManchong_1/skill/LuaJunxing2.ogg
  image/heroskin/audio/JieManchong_1/skill/LuaYuce1.ogg
  image/heroskin/audio/JieManchong_1/skill/LuaYuce2.ogg
  image/heroskin/fullskin/generals/full/JieManchong_1.png
  image/heroskin/generals/card/JieManchong_1.jpg
  image/heroskin/lang/zh_CN/Audio/StandardGeneralPackageLines.lua
  lang/zh_CN/Audio/ExpansionPackageLines.lua
Labels: general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#683 fix: 修正 AI 不发动【峻刑】问题
  lua/ai/ExpansionPackage-ai.lua
Labels: bug, general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky

#685 feat: 添加孙邵
  .gitignore
  Generals.md
  audio/skill/ExSunshao.ogg
  audio/skill/LuaDingyi1.ogg
  audio/skill/LuaDingyi2.ogg
  audio/skill/LuaFubi1.ogg
  audio/skill/LuaFubi2.ogg
  audio/skill/LuaZuici1.ogg
  audio/skill/LuaZuici2.ogg
  extensions/GroupFriendPackage.lua
  extensions/LayingPlansSincerityPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  image/fullskin/generals/full/ExSunshao.png
  image/generals/card/ExSunshao.jpg
  image/mark/@LuaDingyi.png
  image/mark/@LuaFubi.png
  lang/zh_CN/Audio/LayingPlansWisdomPackageLines.lua
  lang/zh_CN/Package/ExpansionConfig.lua
  lang/zh_CN/Package/ExpansionPackage.lua
  lang/zh_CN/Package/GroupFriendPackage.lua
  lang/zh_CN/Package/LayingPlansCouragePackage.lua
  lang/zh_CN/Package/LayingPlansSincerityPackage.lua
  lang/zh_CN/Package/LayingPlansWisdomPackage.lua
  lang/zh_CN/Package/StrategicAttackAbilityPackage.lua
  lang/zh_CN/Package/StrategicAttackPreviewPackage.lua
  lang/zh_CN/Package/StrategicAttackShacklePackage.lua
  lang/zh_CN/Package/StrategicAttackTogetherPackage.lua
  lua/QSanguoshaLuaFunction.lua
  lua/config.lua
Labels: enhancement, 🔍 Ready for Review, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#691 feat: 添加裴秀
  Generals.md
  audio/skill/ExPeixiu.ogg
  audio/skill/LuaJuezhi1.ogg
  audio/skill/LuaJuezhi2.ogg
  audio/skill/LuaXingtu1.ogg
  audio/skill/LuaXingtu2.ogg
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/ExPeixiu.png
  image/generals/card/ExPeixiu.jpg
  image/mark/@LuaXingtu.png
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: enhancement, 🔍 Ready for Review, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#690 feat: 添加荀谌
  Generals.md
  audio/skill/ExXunchen.ogg
  audio/skill/LuaChenshi1.ogg
  audio/skill/LuaChenshi2.ogg
  audio/skill/LuaMoushi1.ogg
  audio/skill/LuaMoushi2.ogg
  audio/skill/LuaWeipo1.ogg
  audio/skill/LuaWeipo2.ogg
  extensions/ExpansionCardPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  extensions/ShieldPackage.lua
  image/fullskin/generals/full/ExXunchen.png
  image/generals/card/ExXunchen.jpg
  image/mark/@LuaMoushiClub.png
  image/mark/@LuaMoushiDiamond.png
  image/mark/@LuaMoushiHeart.png
  image/mark/@LuaMoushiSpade.png
  image/mark/@LuaWeipo.png
  lang/zh_CN/Audio/LayingPlansWisdomPackageLines.lua
  lang/zh_CN/Package/ExpansionCardPackage.lua
  lang/zh_CN/Package/LayingPlansWisdomPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, general fix, ✅ Approved, 🌵 Cactusssssssss

#692 fix: 调整从牌堆拿牌效果
  extensions/LayingPlansWisdomPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: bug, general fix, ✅ Approved

#694 fix: 修正【合计】选择【决斗】时 pattern 不正确的问题
  extensions/LayingPlansSincerityPackage.lua
Labels: bug, ✅ Approved

#695 fix: 调整【合击】目标不能为自己
  extensions/LayingPlansSincerityPackage.lua
Labels: general fix, ✅ Approved

#697 feat: 添加王双
  Generals.md
  audio/skill/ExWangshuang.ogg
  audio/skill/LuaShanxie1.ogg
  audio/skill/LuaShanxie2.ogg
  audio/skill/LuaYiyong1.ogg
  audio/skill/LuaYiyong2.ogg
  extensions/LayingPlansCouragePackage.lua
  extensions/StrategicAttackShacklePackage.lua
  image/fullskin/generals/full/ExWangshuang.png
  image/generals/card/ExWangshuang.jpg
  lang/zh_CN/Audio/LayingPlansCouragePackageLines.lua
  lang/zh_CN/Package/LayingPlansCouragePackage.lua
  lua/ai/LayingPlansCouragePackage-ai.lua
Labels: enhancement, general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#698 fix: 修正王双不能获取其他人装备问题
  extensions/LayingPlansCouragePackage.lua
Labels: bug, ✅ Approved

#699 fix: 修正神太史慈【神著】多次选择二选项后新回合不能出杀问题
  extensions/LayingPlansSincerityPackage.lua
Labels: bug, general fix

#701 fix: 【勤政】不再从弃牌堆获取牌，调整记录标记
  image/mark/@LuaQinzheng.png
  lua/QSanguoshaLuaFunction.lua
Labels: general fix, 🔍 Ready for Review, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#703 ci: Draft PR 不再触发邮件通知流程
  .github/workflows/email-notification.yml
Labels: github issue, ✅ Approved

#705 fix: 调整技能卡显示信息
  extensions/DevineForcePackage.lua
  extensions/ExpansionPackage.lua
  extensions/GroupFriendPackage.lua
  extensions/LayingPlansCouragePackage.lua
  extensions/LayingPlansSincerityPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  extensions/StrategicAttackAbilityPackage.lua
  extensions/StrategicAttackKnowledgePackage.lua
  extensions/StrategicAttackPreviewPackage.lua
  extensions/StrategicAttackShacklePackage.lua
  extensions/StrategicAttackTogetherPackage.lua
Labels: ✅ Approved, 👨‍🔬 Rinkosanvsky

#702 fix: 修正【合击】表现
  extensions/LayingPlansSincerityPackage.lua
Labels: general fix, ✅ Approved

#706 fix: 系列修正
  extensions/LandlordsPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  lang/zh_CN/Package/ExpansionConfig.lua
  lua/QSanguoshaLuaFunction.lua
Labels: general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#707 fix: 修正护甲导致的闪退问题
  lua/QSanguoshaLuaFunction.lua
Labels: bug, ✅ Approved, 👨‍🔬 Rinkosanvsky

#708 fix: 谋攻篇调整
  extensions/LayingPlansWisdomPackage.lua
  extensions/ShieldPackage.lua
  extensions/StrategicAttackKnowledgePackage.lua
  lang/zh_CN/Package/StrategicAttackKnowledgePackage.lua
Labels: general fix, ✅ Approved, 🌵 Cactusssssssss

#710 fix: 修正【合击】距离限制
  extensions/LayingPlansSincerityPackage.lua
Labels: bug, ✅ Approved

#711 fix: 修正获取牌
  extensions/LayingPlansWisdomPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: bug, ✅ Approved

#712 fix: 修正谋曹操【奸雄】无标记依然询问是否移除问题
  extensions/StrategicAttackPreviewPackage.lua
Labels: general fix, ✅ Approved, 👨‍🔬 Rinkosanvsky

#713 fix: 调整星徐晃【治严】AI
  lua/ai/ExpansionPackage-ai.lua
Labels: general fix, 🔍 Ready for Review, 👨‍🔬 Rinkosanvsky

#717 feat:添加手杀界公孙瓒，顺便改曹昂皮肤
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/JieGongsunzan.png
  image/generals/card/JieGongsunzan.jpg
  image/heroskin/generals/card/caoang_1.jpg
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: ✅ Approved, 👨‍🔬 Rinkosanvsky

#718 fix: 调整斗地主流程，增加叫分环节
  extensions/ImpassePackage.lua
  extensions/LandlordsPackage.lua
  lang/zh_CN/Package/LandlordsPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, general fix, ✅ Approved, 🌵 Cactusssssssss

#716 feat: 添加曹嵩
  Generals.md
  audio/skill/ExCaosong.ogg
  audio/skill/LuaGuanzong1.ogg
  audio/skill/LuaGuanzong2.ogg
  audio/skill/LuaYijin1.ogg
  audio/skill/LuaYijin2.ogg
  audio/skill/LuaYijin3.ogg
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/ExCaosong.png
  image/generals/card/ExCaosong.jpg
  image/mark/@LuaYijin1.png
  image/mark/@LuaYijin2.png
  image/mark/@LuaYijin3.png
  image/mark/@LuaYijin4.png
  image/mark/@LuaYijin5.png
  image/mark/@LuaYijin6.png
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: enhancement, ✅ Approved, 🌵 Cactusssssssss

#719 ci: 发布 tag 自动打包并 release
  .github/workflows/auto-release.yml
Labels: github issue, ✅ Approved

#721 ci: 重新调整自动打包 workflow 流程
  .github/workflows/auto-release.yml
Labels: github issue, ✅ Approved, 👨‍🔬 Rinkosanvsky

#726 docs: 添加潘濬【观微】修正指南
  README.md
Labels: documentation, ✅ Approved

#727 feat: 添加蒲元
  .gitignore
  Generals.md
  audio/skill/ExPuyuan.ogg
  audio/skill/LuaTianjiang1.ogg
  audio/skill/LuaTianjiang2.ogg
  audio/skill/LuaZhuren1.ogg
  audio/skill/LuaZhuren2.ogg
  extensions/ExtraordinaryPeoplePackage.lua
  extensions/PuyuanEquipCardPackage.lua
  extensions/StrategicAttackShacklePackage.lua
  image/big-card/poison_knife.png
  image/big-card/quench_blade.png
  image/big-card/red_satin_spear.png
  image/big-card/ripple_sword.png
  image/big-card/thunder_blade.png
  image/card/poison_knife.png
  image/card/quench_blade.png
  image/card/red_satin_spear.png
  image/card/ripple_sword.png
  image/card/thunder_blade.png
  image/equips/poison_knife.png
  image/equips/quench_blade.png
  image/equips/red_satin_spear.png
  image/equips/ripple_sword.png
  image/equips/thunder_blade.png
  image/fullskin/generals/full/ExPuyuan.png
  image/fullskin/small-equips/poison_knife.png
  image/fullskin/small-equips/quench_blade.png
  image/fullskin/small-equips/red_satin_spear.png
  image/fullskin/small-equips/ripple_sword.png
  image/fullskin/small-equips/thunder_blade.png
  image/generals/card/ExPuyuan.jpg
  image/small-equips/poison_knife.png
  image/small-equips/quench_blade.png
  image/small-equips/red_satin_spear.png
  image/small-equips/thunder_blade.png
  lang/zh_CN/Audio/ExtraordinaryPeoplePackageLines.lua
  lang/zh_CN/Package/ExtraordinaryPeoplePackage.lua
  lang/zh_CN/Package/PuyuanEquipCardPackage.lua
  lua/QSanguoshaLuaFunction.lua
  lua/ai/PuyuanEquipCardPackage-ai.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#728 feat: 添加重制版贾逵
  Generals.md
  audio/skill/ExTongquJiakui.ogg
  audio/skill/LuaTongqu1.ogg
  audio/skill/LuaTongqu2.ogg
  audio/skill/LuaWanlanTongqu1.ogg
  audio/skill/LuaWanlanTongqu2.ogg
  extensions/ExpansionPackage.lua
  extensions/StrategicAttackKnowledgePackage.lua
  image/fullskin/generals/full/ExTongquJiakui.png
  image/generals/card/ExTongquJiakui.jpg
  image/mark/@LuaTongqu.png
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
  lang/zh_CN/Package/StrategicAttackKnowledgePackage.lua
  lua/ai/ExpansionPackage-ai.lua
Labels: ✅ Approved, 🌵 Cactusssssssss

#729 fix: 技能提示文本修正
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: general fix, ✅ Approved, 🌵 Cactusssssssss

#731 fix: 系列 bug 修正
  extensions/ExpansionPackage.lua
  extensions/PuyuanEquipCardPackage.lua
Labels: bug, ✅ Approved, 👨‍🔬 Rinkosanvsky

#732 fix: 修正死亡后移出游戏
  extensions/PuyuanEquipCardPackage.lua
Labels: ✅ Approved, 👨‍🔬 Rinkosanvsky

#734 feat: 添加系列皮肤
  .gitignore
  extensions/ExpansionPackage.lua
  image/heroskin/audio/ExStarGanning_1/death/ExStarGanning.ogg
  image/heroskin/audio/ExStarGanning_1/skill/LuaJinfan1.ogg
  image/heroskin/audio/ExStarGanning_1/skill/LuaJinfan2.ogg
  image/heroskin/audio/ExStarGanning_1/skill/LuaSheque1.ogg
  image/heroskin/audio/ExStarGanning_1/skill/LuaSheque2.ogg
  image/heroskin/audio/ExYangbiao_2/death/ExYangbiao.ogg
  image/heroskin/audio/ExYangbiao_2/skill/LuaRangjie1.ogg
  image/heroskin/audio/ExYangbiao_2/skill/LuaRangjie2.ogg
  image/heroskin/audio/ExYangbiao_2/skill/LuaYizheng1.ogg
  image/heroskin/audio/ExYangbiao_2/skill/LuaYizheng2.ogg
  image/heroskin/audio/ExYangbiao_2/skill/LuaZhaohan1.ogg
  image/heroskin/audio/ExYangbiao_2/skill/LuaZhaohan2.ogg
  image/heroskin/audio/ol_xuyou_2/death/ol_xuyou.ogg
  image/heroskin/audio/ol_xuyou_2/skill/chenglve1.ogg
  image/heroskin/audio/ol_xuyou_2/skill/chenglve2.ogg
  image/heroskin/audio/ol_xuyou_2/skill/cunmu1.ogg
  image/heroskin/audio/ol_xuyou_2/skill/cunmu2.ogg
  image/heroskin/audio/ol_xuyou_2/skill/ol_shicai1.ogg
  image/heroskin/audio/ol_xuyou_2/skill/ol_shicai2.ogg
  image/heroskin/audio/zhangrang_1/death/zhangrang.ogg
  image/heroskin/audio/zhangrang_1/skill/taoluan1.ogg
  image/heroskin/audio/zhangrang_1/skill/taoluan2.ogg
  image/heroskin/fullskin/generals/full/ExStarGanning_1.png
  image/heroskin/fullskin/generals/full/ExYangbiao_2.png
  image/heroskin/fullskin/generals/full/ol_xuyou_2.png
  image/heroskin/fullskin/generals/full/zhangrang_1.png
  image/heroskin/generals/card/ExStarGanning_1.jpg
  image/heroskin/generals/card/ExYangbiao_2.jpg
  image/heroskin/generals/card/ol_xuyou_2.jpg
  image/heroskin/generals/card/zhangrang_1.jpg
  image/heroskin/lang/zh_CN/Audio/StandardGeneralPackageLines.lua
Labels: enhancement, general fix, 🔍 Ready for Review, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#736 feat: 添加 OL 界赵云
  Generals.md
  audio/skill/LuaOLLongdan1.ogg
  audio/skill/LuaOLLongdan2.ogg
  audio/skill/LuaOLYajiao1.ogg
  audio/skill/LuaOLYajiao2.ogg
  audio/skill/OLJieZhaoyun.ogg
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/OLJieZhaoyun.png
  image/generals/card/OLJieZhaoyun.jpg
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: enhancement, ✅ Approved, 🌵 Cactusssssssss
