Repository DZDcyj/QSGS-v2-Lua, pull requests merged in 2023-06, with the labels that each got.

#768 fix: 文本修正
  lang/zh_CN/Package/LayingPlansStrictnessPackage.lua
Labels: general fix, ✅ Approved, 🌵 Cactusssssssss

#770 fix: 修正【涯角】展示框不消失问题
  extensions/OLBoundaryBreachStandardPackage.lua
Labels: bug, ✅ Approved

#772 feat: 添加星黄忠
  Generals.md
  audio/skill/ExStarHuangzhong.ogg
  audio/skill/LuaQishe1.ogg
  audio/skill/LuaQishe2.ogg
  audio/skill/LuaShidi1.ogg
  audio/skill/LuaShidi2.ogg
  audio/skill/LuaStarYishi1.ogg
  audio/skill/LuaStarYishi2.ogg
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/ExStarHuangzhong.png
  image/generals/card/ExStarHuangzhong.jpg
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#777 fix: 修改了皇甫嵩、朱儁整肃相关的技能描述
  image/fullskin/generals/full/ExHuangfusong.png
  image/fullskin/generals/full/ExJiakui.png
  lang/zh_CN/Package/LayingPlansStrictnessPackage.lua
Labels: ✅ Approved, 👨‍🔬 Rinkosanvsky
