Repository DZDcyj/QSGS-v2-Lua, pull requests merged in 2023-05, with the labels that each got.

#740 feat: 添加界卧龙诸葛
  Generals.md
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/JieWolong.png
  image/generals/card/JieWolong.jpg
  lang/zh_CN/Package/ExpansionPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#744 Bossrushmode
  lua/config.lua
Labels: ✅ Approved, 👨‍🔬 Rinkosanvsky

#742 refactor: 武将包拆分与方法重构
  .gitignore
  Generals.md
  extensions/BeholdHighMountainPackage.lua
  extensions/BraveWarriorsPackage.lua
  extensions/ExpansionCardPackage.lua
  extensions/ExpansionPackage.lua
  extensions/GoodMatchPackage.lua
  extensions/GroupFriendPackage.lua
  extensions/LayingPlansSincerityPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  extensions/OLBoundaryBreachFirePackage.lua
  extensions/OLBoundaryBreachStandardPackage.lua
  extensions/PrayFortunePackage.lua
  extensions/PuyuanEquipCardPackage.lua
  extensions/StrategicAttackKnowledgePackage.lua
  extensions/StrategicAttackPreviewPackage.lua
  image/fullskin/generals/full/ExTenYearDongcheng.png
  image/generals/card/ExTenYearDongcheng.jpg
  lang/zh_CN/Audio/BeholdHighMountainPackageLines.lua
  lang/zh_CN/Audio/BraveWarriorsPackageLines.lua
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Audio/GoodMatchPackageLines.lua
  lang/zh_CN/Audio/OLBoundaryBreachFirePackageLines.lua
  lang/zh_CN/Audio/OLBoundaryBreachStandardPackageLines.lua
  lang/zh_CN/Audio/PrayFortunePackageLines.lua
  lang/zh_CN/Package/BeholdHighMountainPackage.lua
  lang/zh_CN/Package/BraveWarriorsPackage.lua
  lang/zh_CN/Package/ExpansionPackage.lua
  lang/zh_CN/Package/GoodMatchPackage.lua
  lang/zh_CN/Package/OLBoundaryBreachFirePackage.lua
  lang/zh_CN/Package/OLBoundaryBreachStandardPackage.lua
  lang/zh_CN/Package/PrayFortunePackage.lua
  lua/QSanguoshaLuaFunction.lua
  lua/ai/BeholdHighMountainPackage-ai.lua
  lua/ai/BraveWarriorsPackage-ai.lua
  lua/ai/ExpansionPackage-ai.lua
  lua/ai/PrayFortunePackage-ai.lua
Labels: structure, ✅ Approved, 🌵 Cactusssssssss

#745 feat: 添加 OL 界李典
  Generals.md
  audio/skill/LuaOLWangxi1.ogg
  audio/skill/LuaOLWangxi2.ogg
  audio/skill/OLJieLidian.ogg
  extensions/OLBoundaryBreachStandardPackage.lua
  image/fullskin/generals/full/OLJieLidian.png
  image/generals/card/OLJieLidian.jpg
  lang/zh_CN/Audio/OLBoundaryBreachStandardPackageLines.lua
  lang/zh_CN/Package/OLBoundaryBreachStandardPackage.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#746 feat: 添加界祝融
  Generals.md
  audio/skill/JieZhurong.ogg
  audio/skill/LuaJuxiang1.ogg
  audio/skill/LuaJuxiang2.ogg
  audio/skill/LuaLieren1.ogg
  audio/skill/LuaLieren2.ogg
  extensions/ExpansionPackage.lua
  image/fullskin/generals/full/JieZhurong.png
  image/generals/card/JieWolong.jpg
  image/generals/card/JieZhurong.jpg
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Package/ExpansionPackage.lua
Labels: enhancement, general fix, ✅ Approved, 🌵 Cactusssssssss

#747 fix: 修正界祝融性别与巨象 bug
  extensions/ExpansionPackage.lua
Labels: bug, general fix, ✅ Approved

#754 Fix pic＆lang
  audio/skill/ExSufei.ogg
  audio/skill/LuaGaoyuan1.ogg
  audio/skill/LuaGaoyuan2.ogg
  audio/skill/LuaZhengjian1.ogg
  audio/skill/LuaZhengjian2.ogg
  image/fullskin/generals/full/ExGaolan.png
  image/fullskin/generals/full/ExMouZhouyu.png
  image/fullskin/generals/full/ExPeixiu.png
  image/fullskin/generals/full/ExSufei.png
  image/fullskin/generals/full/ExSunyi.png
  image/fullskin/generals/full/ExWangshuang.png
  image/fullskin/generals/full/ExZhangyi.png
  image/fullskin/generals/full/ExZhujun.png
  image/fullskin/generals/full/JieLiaohua.png
  image/fullskin/generals/full/JieYujin.png
  image/generals/card/ExSufei.jpg
  image/heroskin/audio/ExSufei_1/death/ExSufei.ogg
  image/heroskin/audio/ExSufei_1/skill/LuaGaoyuan1.ogg
  image/heroskin/audio/ExSufei_1/skill/LuaGaoyuan2.ogg
  image/heroskin/audio/ExSufei_1/skill/LuaZhengjian1.ogg
  image/heroskin/audio/ExSufei_1/skill/LuaZhengjian2.ogg
  image/heroskin/fullskin/generals/full/ExSufei_1.png
  image/heroskin/generals/card/ExSufei_1.jpg
  image/heroskin/lang/zh_CN/Audio/StandardGeneralPackageLines.lua
  lang/zh_CN/Audio/ExpansionPackageLines.lua
  lang/zh_CN/Audio/LayingPlansStrictnessPackageLines.lua
  lang/zh_CN/Package/LayingPlansStrictnessPackage.lua
Labels: ✅ Approved, 👨‍🔬 Rinkosanvsky

#753 feat: 添加皇甫嵩
  Generals.md
  audio/skill/ExHuangfusong.ogg
  audio/skill/LuaShiji1.ogg
  audio/skill/LuaShiji2.ogg
  audio/skill/LuaTaoluan1.ogg
  audio/skill/LuaTaoluan2.ogg
  audio/skill/LuaZhengjun1.ogg
  audio/skill/LuaZhengjun2.ogg
  audio/skill/LuaZhengjun3.ogg
  extensions/LayingPlansStrictnessPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  extensions/RectificationPackage.lua
  image/fullskin/generals/full/ExHuangfusong.png
  image/generals/card/ExHuangfusong.jpg
  lang/zh_CN/Audio/LayingPlansStrictnessPackageLines.lua
  lang/zh_CN/Package/LayingPlansStrictnessPackage.lua
  lang/zh_CN/Package/RectificationPackage.lua
Labels: enhancement, ✅ Approved, 🌵 Cactusssssssss

#755 refactor: 公共方法重构
  extensions/BeholdHighMountainPackage.lua
  extensions/BraveWarriorsPackage.lua
  extensions/DevineForcePackage.lua
  extensions/ExpansionPackage.lua
  extensions/ExtraordinaryPeoplePackage.lua
  extensions/GoodMatchPackage.lua
  extensions/GroupFriendPackage.lua
  extensions/ImpassePackage.lua
  extensions/LandlordsPackage.lua
  extensions/LayingPlansCouragePackage.lua
  extensions/LayingPlansSincerityPackage.lua
  extensions/LayingPlansStrictnessPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  extensions/OLBoundaryBreachFirePackage.lua
  extensions/PrayFortunePackage.lua
  extensions/PuyuanEquipCardPackage.lua
  extensions/RectificationPackage.lua
  extensions/ShieldPackage.lua
  extensions/StrategicAttackAbilityPackage.lua
  extensions/StrategicAttackKnowledgePackage.lua
  extensions/StrategicAttackPreviewPackage.lua
  extensions/StrategicAttackShacklePackage.lua
  extensions/StrategicAttackTogetherPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: structure, ✅ Approved, 👨‍🔬 Rinkosanvsky

#756 refactor: 优化整肃成功部分
  extensions/RectificationPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: general fix, structure, ✅ Approved, 👨‍🔬 Rinkosanvsky

#758 feat: 添加吕范
  Generals.md
  audio/skill/ExLvfan.ogg
  audio/skill/LuaDiancai1.ogg
  audio/skill/LuaDiancai2.ogg
  audio/skill/LuaDiaodu1.ogg
  audio/skill/LuaDiaodu2.ogg
  audio/skill/LuaYanji1.ogg
  audio/skill/LuaYanji2.ogg
  audio/skill/LuaYanji3.ogg
  extensions/LayingPlansStrictnessPackage.lua
  extensions/RectificationPackage.lua
  image/fullskin/generals/full/ExLvfan.png
  image/generals/card/ExLvfan.jpg
  lang/zh_CN/Audio/LayingPlansStrictnessPackageLines.lua
  lang/zh_CN/Package/LayingPlansStrictnessPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss

#760 fix: 修正【秉清】失效问题
  extensions/ExpansionPackage.lua
Labels: bug, general fix, 🔍 Ready for Review

#761 fix: 技能与引用修正
  extensions/LayingPlansSincerityPackage.lua
  extensions/LayingPlansWisdomPackage.lua
  extensions/PrayFortunePackage.lua
  extensions/StrategicAttackPreviewPackage.lua
Labels: bug, general fix, ✅ Approved

#762 feat: 添加崔琰
  Generals.md
  audio/skill/ExCuiyan.ogg
  audio/skill/LuaYajun1.ogg
  audio/skill/LuaYajun2.ogg
  audio/skill/LuaZundi1.ogg
  audio/skill/LuaZundi2.ogg
  extensions/LayingPlansStrictnessPackage.lua
  image/fullskin/generals/full/ExCuiyan.png
  image/generals/card/ExCuiyan.jpg
  lang/zh_CN/Audio/LayingPlansStrictnessPackageLines.lua
  lang/zh_CN/Audio/OLBoundaryBreachStandardPackageLines.lua
  lang/zh_CN/Package/LayingPlansStrictnessPackage.lua
  lua/QSanguoshaLuaFunction.lua
Labels: enhancement, ✅ Approved, 👨‍🔬 Rinkosanvsky, 🌵 Cactusssssssss
